### ISSUE TITLE
Unable to load homebridge  following install of homebridge controller

### ISSUE THREAD

**Issue by miguelmolez** [KraigM/HomeBridgeController#63]
After installing homebridge and updating one of my hubs, I get the following error..

Error: bind EADDRINUSE 0.0.0.0:5224
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at dgram.js:213:18
    at doNTCallback3 (node.js:440:9)
    at process._tickCallback (node.js:346:17)
    at Function.Module.runMain (module.js:477:11)
    at startup (node.js:117:18)
    at node.js:951:3

Any help appreciated.
Thanks

**Comment by PatchworkBoy** [comment]
Ditto... 

`[Mon Aug 22 2016 19:32:29 GMT+0100 (BST)] Loading 0 accessories...
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1129:14)
    at listen (net.js:1155:10)
    at Server.listen (net.js:1240:5)
    at tryCatcher (/usr/local/lib/node_modules/homebridge-controllerlink/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.fromNode.Promise.fromCallback (/usr/local/lib/node_modules/homebridge-controllerlink/node_modules/bluebird/js/release/promise.js:176:30)
    at Server.startAsync (/usr/local/lib/node_modules/homebridge-controllerlink/lib/server.js:113:11)
    at Object.HomeBridgeControllerLink.accessories (/usr/local/lib/node_modules/homebridge-controllerlink/index.js:34:15)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:333:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:277:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:71:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)`

Occasionally homebridgecontroller (or bluebird & an unresolved promise) causes homebridge not to exit cleanly, leaving the homebridgecontroller port still in use. This then prevents relaunch of homebridge until the original stalled homebridge process has died or been manually killed.
