### ISSUE TITLE
After update and subsequent rollback I can't launch hombridge with controller installed. 

### ISSUE THREAD

**Issue by jimprintsthings** [KraigM/HomeBridgeController#64]
I get this when HomeBridgeControllerLink is enabled.  This had worked previously.

path.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.resolve (path.js:426:5)
    at Conf.loadPrefix (/usr/local/lib/node_modules/homebridge-controllerlink/node_modules/npm/lib/config/load-prefix.js:43:14)
    at load_ (/usr/local/lib/node_modules/homebridge-controllerlink/node_modules/npm/lib/config/core.js:109:8)
    at Conf.<anonymous> (/usr/local/lib/node_modules/homebridge-controllerlink/node_modules/npm/lib/config/core.js:96:5)
    at emitOne (events.js:77:13)
    at Conf.emit (events.js:169:7)
    at ConfigChain._resolve (/usr/local/lib/node_modules/homebridge-controllerlink/node_modules/npm/node_modules/config-chain/index.js:281:34)
    at ConfigChain.add (/usr/local/lib/node_modules/homebridge-controllerlink/node_modules/npm/node_modules/config-chain/index.js:259:10)
    at Conf.add (/usr/local/lib/node_modules/homebridge-controllerlink/node_modules/npm/lib/config/core.js:341:27)
    at Conf.<anonymous> (/usr/local/lib/node_modules/homebridge-controllerlink/node_modules/npm/lib/config/core.js:320:25)
    at ReadFileContext.callback (/usr/local/lib/node_modules/homebridge-controllerlink/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete](fs.js:303:13)

**Comment by JangoBritt** [comment]
FYI, I'm getting this too

**Comment by frodeaux** [comment]
same here

**Comment by jimprintsthings** [comment]
Ohh sweet.  At least I"m not alone.  It was working prior.

**Comment by ovq** [comment]
same here.

**Comment by JangoBritt** [comment]
Oh Dear. @KraigM, sounds like there may be a recurring issue. Happy to help Debug.

**Comment by jimprintsthings** [comment]
Happy to provide logs/whatever you need.

**Comment by Dazzzz** [comment]
Same here. I had Homebridge working great, but I wanted to install HomeBridgeController as well to fix Celcius/ Fahrenheit issues, but I can't get HomeBridge to load now.

**Comment by Chioti** [comment]
Same issue for me.

**Comment by a2sheppy** [comment]
Similar here. I had it running when I was using my Mac as a homebridge station, but when I switched to Pi, it broke and I get this error. FWIW, I get this error on several plugins, not just the homebridge-controllerlink one.

**Comment by a2sheppy** [comment]
Looking through things, I wonder: could it be using the wrong `node` to run homebridge? There are at least two copies installed: one at /usr/bin/node and the one installed under the pi user that's intended to be used.

**Comment by jaredmichaelwilliams** [comment]
I was able to fix this by doing the following:

on line 43 of  `/usr/local/lib/node_modules/homebridge-controllerlink/node_modules/npm/lib/config/load-prefix.js`

i changed: 

`p = path.resolve(cli.prefix)` 

to 

`p = path.resolve(String(cli.prefix))`

and on line 21 of `/usr/local/lib/node_modules/homebridge-controllerlink/node_modules/npm/lib/config/set-user.js`

i changed

 `var prefix = path.resolve(this.get('prefix'))` 

 to   

`var prefix = path.resolve(String(this.get('prefix')))`

**Comment by RickNunn** [comment]
@jaredmichaelwilliams this fixed my issue too!

**Comment by Chioti** [comment]
And for me as well. Thanks!

**Comment by jimprintsthings** [comment]
@jaredmichaelwilliams This worked here as well. Thank you.

**Comment by livefeed** [comment]
@jaredmichaelwilliams Thank you!!!!! the fix worked for me.

**Comment by rhapsfx** [comment]
Thanks for the fix. Can it be published to the source ?

**Comment by IMNotMax** [comment]
Thnx for the fix !
