### ISSUE TITLE
ERROR:  Path must be a string 

### ISSUE THREAD

**Issue by frodeaux** [KraigM/HomeBridgeController#65]
I love this plugin but I am attempting to install on a fresh Pi and I can not get it to run.  Here are the details and the error it is giving me. I even installed a nest and an eco plug and was able to run them fine. Whenever the homebrige-controllerlink gets setup and put into the config, home bridge bombs.
Any advice would be appreciated. I have tried uninstalling and reinstalling with no luck !

Hardware: Raspberry Pi3  Running Jessie 8.0
Node Version: v4.6.0
NPM Version: 2.15.9

Config File:  (JSON check out just fine)

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:33:3D:E3:CE:01",
        "port": 51826,
        "pin": "333-33-333"
    },

    "description": "This is the COREPI3 Homebridge Configuration File",

    "platforms": [{
        "platform": "HomeBridgeControllerLink",
        "restartStyle": "stopOnly",
        "disableAutoRestart": false,
        "disableLogger": false
    }, {
        "platform": "Nest",
        "token": "xxxxxxx",
        "clientId": "xxxxxxxxx",
        "clientSecret": "xxxxxxxxx",
        "code": "xxxxxxxx",
        "username": "xxxxxxxx@gmail.com",
        "password": "xxxxxxx"
    }],

    "accessories": [{
        "accessory": "EcoPlug",
        "name": "TEST PLUG",
        "host": "10.0.1.220",
        "id": "ECO-7800D323"
    }]
}

```

ERROR:

> homebridge@COREPI3:~$ homebridge -U /var/homebridge
> **\* WARNING **\* The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
> **\* WARNING **\* Please fix your application to use the native API of Avahi!
> **\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs
> **\* WARNING **\* The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
> **\* WARNING **\* Please fix your application to use the native API of Avahi!
> **\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister
> **\* WARNING **\* The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
> **\* WARNING **\* Please fix your application to use the native API of Avahi!
> **\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister
> [10/7/2016, 12:16:14 PM] Loaded plugin: homebridge-controllerlink
> [10/7/2016, 12:16:14 PM] Registering platform 'homebridge-controllerlink.HomeBridgeControllerLink'
> [10/7/2016, 12:16:14 PM] ---
> [10/7/2016, 12:16:14 PM] Loaded plugin: homebridge-ecoplug
> [10/7/2016, 12:16:14 PM] Registering accessory 'homebridge-ecoplugs.EcoPlug'
> [10/7/2016, 12:16:14 PM] ---
> [10/7/2016, 12:16:15 PM] Loaded plugin: homebridge-nest
> [10/7/2016, 12:16:15 PM] Registering platform 'homebridge-nest.Nest'
> [10/7/2016, 12:16:15 PM] ---
> [10/7/2016, 12:16:15 PM] Loaded config.json with 1 accessories and 2 platforms.
> [10/7/2016, 12:16:15 PM] ---
> [10/7/2016, 12:16:15 PM] Loading 2 platforms...
> [10/7/2016, 12:16:15 PM] Initializing HomeBridgeControllerLink platform...
> [10/7/2016, 12:16:15 PM] Initializing Nest platform...
> [10/7/2016, 12:16:15 PM] Fetching Nest devices.
> [10/7/2016, 12:16:15 PM] Loading 1 accessories...
> [10/7/2016, 12:16:15 PM] [TEST PLUG] Initializing EcoPlug accessory...
> path.js:8
>     throw new TypeError('Path must be a string. Received ' +
>     ^
> 
> TypeError: Path must be a string. Received undefined
>     at assertPath (path.js:8:11)
>     at Object.posix.resolve (path.js:426:5)
>     at Conf.loadPrefix (/usr/lib/node_modules/homebridge-controllerlink/node_modules/npm/lib/config/load-prefix.js:43:14)
>     at load_ (/usr/lib/node_modules/homebridge-controllerlink/node_modules/npm/lib/config/core.js:109:8)
>     at Conf.<anonymous> (/usr/lib/node_modules/homebridge-controllerlink/node_modules/npm/lib/config/core.js:96:5)
>     at emitOne (events.js:77:13)
>     at Conf.emit (events.js:169:7)
>     at ConfigChain._resolve (/usr/lib/node_modules/homebridge-controllerlink/node_modules/npm/node_modules/config-chain/index.js:281:34)
>     at ConfigChain.add (/usr/lib/node_modules/homebridge-controllerlink/node_modules/npm/node_modules/config-chain/index.js:259:10)
>     at Conf.add (/usr/lib/node_modules/homebridge-controllerlink/node_modules/npm/lib/config/core.js:341:27)
>     at Conf.<anonymous> (/usr/lib/node_modules/homebridge-controllerlink/node_modules/npm/lib/config/core.js:320:25)
>     at ReadFileContext.callback (/usr/lib/node_modules/homebridge-controllerlink/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16)
>     at FSReqWrap.readFileAfterOpen [as oncomplete](fs.js:303:13)

**Comment by JangoBritt** [comment]
same error as issue #64

**Comment by RickNunn** [comment]
+1 to this issue :(

**Comment by LMoesman3004** [comment]
same error

**Comment by livefeed** [comment]
I am getting this error, do we know of a fix to it?
