### ISSUE TITLE
Cannot start with latest homebridge?

### ISSUE THREAD

**Issue by troystanway** [KraigM/HomeBridgeController#67]
Hi, When launching with latest build and latest home bridge on jessie, I get this error all the time when running homebridge: (I have tried npm uninstall and reinstall)

```
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1188:7)
    at Conf.loadPrefix (/usr/local/lib/node_modules/homebridge-controllerlink/node_modules/npm/lib/config/load-prefix.js:43:14)
    at load_ (/usr/local/lib/node_modules/homebridge-controllerlink/node_modules/npm/lib/config/core.js:109:8)
    at Conf.<anonymous> (/usr/local/lib/node_modules/homebridge-controllerlink/node_modules/npm/lib/config/core.js:96:5)
    at emitOne (events.js:90:13)
    at Conf.emit (events.js:182:7)
    at ConfigChain._resolve (/usr/local/lib/node_modules/homebridge-controllerlink/node_modules/npm/node_modules/config-chain/index.js:281:34)
    at ConfigChain.add (/usr/local/lib/node_modules/homebridge-controllerlink/node_modules/npm/node_modules/config-chain/index.js:259:10)
    at Conf.add (/usr/local/lib/node_modules/homebridge-controllerlink/node_modules/npm/lib/config/core.js:341:27)
    at Conf.<anonymous> (/usr/local/lib/node_modules/homebridge-controllerlink/node_modules/npm/lib/config/core.js:320:25)
    at ReadFileContext.callback (/usr/local/lib/node_modules/homebridge-controllerlink/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:324:13)
```

**Comment by troystanway** [comment]
After some trial and error I found _jaredmichaelwilliams_ solution to work.
https://github.com/KraigM/HomeBridgeController/issues/64#issuecomment-258587001
